export const blogPosts = [
    {
      id: 1,
      title: "Optimizing Data Management with FileMaker: Tips for Small Businesses",
      date: "2025-01-10",
      slug: "optimizing-data-management-filemaker-tips-small-businesses",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 2,
      title: "The Benefits of API Integration for Small Business Growth",
      date: "2024-12-20",
      slug: "benefits-api-integration-small-business-growth",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 3,
      title: "Best API Integration Plugins for FileMaker Developers",
      date: "2024-11-22",
      slug: "best-api-integration-plugins-filemaker-developers",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 4,
      title: "Top Productivity Tools for Client Relationship Management",
      date: "2024-12-06",
      slug: "top-productivity-tools-client-relationship-management",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 5,
      title: "The Role of Custom Software in Enhancing Supply Chain Management",
      date: "2024-11-08",
      slug: "role-custom-software-enhancing-supply-chain-management",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 6,
      title: "A Comprehensive Guide to API Integration for Business Automation",
      date: "2024-10-18",
      slug: "comprehensive-guide-api-integration-business-automation",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 7,
      title: "The Benefits of Using FileMaker for Custom App Development in Small Businesses",
      date: "2024-10-04",
      slug: "benefits-using-filemaker-custom-app-development-small-businesses",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 8,
      title: "Data Migration and FileMaker: A Consultant's Guide",
      date: "2024-09-20",
      slug: "data-migration-filemaker-consultants-guide",
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      id: 9,
      title: "Best Practices for Data Backup and Recovery in FileMaker",
      date: "2024-08-23",
      slug: "best-practices-data-backup-recovery-filemaker",
      image: "/placeholder.svg?height=200&width=400",
    },
  ]